---
title: "How the Yarn Unraveled!"
subtitle: "Made in America Yarns"
date: "August, 2020"
output: html_document
---

```{r setup, include=FALSE}

#echo=TRUE means that the code shows
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")

library(emojifont)
library(tidyverse)

yearmo <- "202008"

#IMPORT DATA
orders <- read.csv(paste("C:/Users/Owner/repos/miay/data/", yearmo, "/orders_", yearmo, ".csv",sep=""), stringsAsFactors = FALSE)
registrations <- read.csv(paste("C:/Users/Owner/repos/miay/data/", yearmo, "/registrations_", yearmo, ".csv",sep=""), stringsAsFactors = FALSE)
traffic <- read.csv(paste("C:/Users/Owner/repos/miay/data/", yearmo, "/traffic_", yearmo, ".csv",sep=""), stringsAsFactors = FALSE)
coupon <- read.csv(paste("C:/Users/Owner/repos/miay/data/", yearmo, "/coupon_", yearmo, ".csv",sep=""), stringsAsFactors = FALSE)
campaign <- read.csv(paste("C:/Users/Owner/repos/miay/data/", yearmo, "/campaign_", yearmo, ".csv",sep=""), stringsAsFactors = FALSE)

style <- theme(plot.title = element_text(face = "bold", size = 30),
               plot.subtitle = element_text(size = 30),
               axis.title = element_text(size = 25, face="italic"),
               axis.text = element_text(size = 25),
               legend.text = element_text(size = 25),
               legend.title = element_text(face = "bold", size = 25),
               panel.background = element_rect(fill = NA),
               panel.grid.major = element_line(colour = "grey88"),
               axis.ticks = element_line(color=NA))

geom_col_base <- geom_col(fill="darkgoldenrod4", alpha=0.6)

```


# Conversions

```{r message=FALSE, warning=FALSE}

# VALUE BOX (conversions)
#------------------------------>

# assign variables

vb_newsletter_signup <- as.character(sum(traffic$newsletter_sign_up, registrations$customer_registrations))
vb_register <- as.character(sum(registrations$customer_registrations))
vb_new_cust <- as.character(sum(orders$new_customers))

# create df of parameters

df <- data.frame(
  x = seq(2, 22, 10), # position of box
  y = rep(1,3), # position of box
  h = rep(5,3), # size of box
  w = rep(9,3), # size of box
  value = c(vb_newsletter_signup,
            vb_register,
            vb_new_cust),
  info = c("newsletter signups",
           "customer registrations",
           "new customers"),
  font_family = c(rep("EmojiOne", 3)),
  color = factor(1:3)
)

# plot df created above

vb_plot <- function(df){
  df %>% 
  ggplot(aes(x, y, height = h, width = w, label = info)) +
  geom_tile(aes(fill = color)) +
  geom_text(color = "white", fontface = "bold", size = 20, #size of info
            aes(label = value, x = x - 4, y = y + 1), hjust = 0) +
  geom_text(color = "white", fontface = "bold", size = 7,
            aes(label = info, x = x - 4, y = y - 1), hjust = 0) + #size of value
  coord_fixed() +
  scale_fill_brewer(type = "qual",palette = "Dark2") +
  theme_void() +
  guides(fill = FALSE)
}

vb_plot(df)
```


```{r message=FALSE, warning=FALSE}

# PLOT (newsletter signups)

# plot newsletter signups by source

df <- traffic %>% 
  #format source/medium for label
  mutate("source_medium" = paste(source, medium, sep = " / ")) %>%
  #group by source/medium
  group_by(source_medium) %>%
  #sum newsletter_signups by source
  summarise(newsletter_sign_up = sum(newsletter_sign_up)) %>%
  filter(newsletter_sign_up != 0) %>%
  arrange(desc(newsletter_sign_up))

df %>%
  ggplot(aes(x = source_medium,
             y = newsletter_sign_up)) +
    geom_col_base +
  labs(title="newsletter signups",
       x="source / medium",
       y="number of newsletter signups") +
  style + theme(aspect.ratio = 0.6)

```


# Sales

```{r message=FALSE, warning=FALSE}

# VALUE BOX (sales)
#------------------------------>

# assign variables

vb_turnover <- round(sum(orders$turnover),0)
vb_net <- round(sum(orders$net_profit),0)
vb_orders <- sum(orders$orders_placed)
vb_aov <- round(vb_turnover/vb_orders, 0)
vb_ppo <- floor(mean(replace_na(orders$products_purchased/orders$orders_placed, 0)))

# create df of parameters

df <- data.frame(
  x = c(7,17,2,12,22), # position of box
  y = c(7,7,1,1,1), # position of box
  h = rep(5,5), # size of box
  w = rep(9,5), # size of box
  value = c(paste("$", formatC(vb_turnover, format = 'd', big.mark = ','), sep=""),
            paste("$", formatC(vb_net, format = 'd', big.mark = ','), sep=""),
            vb_orders,
            paste("$", formatC(vb_aov, format = 'd', big.mark = ','), sep=""),
            vb_ppo),
  info = c("turnover",
           "net profit",
           "orders placed",
           "average order value",
           "products per order"),
  font_family = c(rep("EmojiOne", 5)),
  color = factor(1:5)
)

vb_plot(df)

```


```{r message=FALSE, warning=FALSE}

# COLUMN CHART (sales)[variable vs sum]
#------------------------------>

vrs <- c("turnover", "net_profit", "coupons", "refunds", "fee_paypal", "shipping_charged",
         "shipping_cost")

df <- orders %>% 
  #calculate totals for month
  summarise(across(all_of(vrs), sum)) %>% 
  #pivot variables to values
  pivot_longer(cols=everything()) %>%
  #reorder variables
  mutate(name = factor(name, levels = c("turnover", 
                                        "net_profit", 
                                        "shipping_charged", 
                                        "shipping_cost", 
                                        "coupons", 
                                        "refunds", 
                                        "fee_paypal")),
         category = case_when(name %in% c("turnover", 
                                          "shipping_charged") ~ "profit",
                              name %in% c("shipping_cost", 
                                          "coupons", 
                                          "refunds", 
                                          "fee_paypal") ~ "loss",
                              name == "net_profit" ~ "net profit"))

cols <- c("profit"="darkolivegreen", 
          "net profit"="darkgoldenrod4",
          "loss"="indianred4")

df %>%
  ggplot(aes(x = name, 
             y = value,
             fill = factor(category))) +
  labs(title="Profits and Losses",
       x="",
       y="") +  
  geom_col(alpha = 0.8) +
  scale_colour_manual(
  values = cols,
  aesthetics = c("color", "fill")) +
  style + theme(legend.position = "bottom")


```

```{r message=FALSE, warning=FALSE}
# COLUMN CART (sales)[day vs orders placed]
#------------------------------>

df <- orders %>% 
  mutate("returning" = abs(orders_placed - new_customers),
         "new" = new_customers) %>%
  select(order_date, 
         returning,
         new) %>%
  pivot_longer(!order_date,
               names_to = "customer_type",
               values_to = "orders_placed") 

cols <- c("new" = "darkolivegreen4",
          "returning" = "darkgreen")

df %>% 
  ggplot(aes(x = order_date, y = orders_placed, fill = factor(customer_type))) +
  labs(title="Orders Placed",
       subtitle = "by New and Returning Customers",
       x="day",
       y="number of orders placed") +
  geom_col(position = "stack", alpha = 0.8) +
  scale_colour_manual(
  values = cols,
  aesthetics = c("color", "fill")) +
  style + theme(legend.position = "bottom")

```

# Traffic

````{r message=FALSE, warning=FALSE}

# VALUE BOX (traffic)
#------------------------------>

# assign variables

vb_users <- sum(traffic$users)
vb_pct_new_users <- round(sum(traffic$new_users)/sum(traffic$users)*100, 0)
vb_pct_view_cart <- round(sum(traffic$view_cart)/sum(traffic$user)*100, 0)
vb_pct_reach_checkout <- round(sum(traffic$reach_checkout)/sum(traffic$user)*100, 0)

# create df of parameters

df <- data.frame(
  x = c(12,2,12,22), # position of box
  y = c(7,1,1,1), # position of box
  h = rep(5,4), # size of box
  w = rep(9,4), # size of box
  value = c(formatC(vb_users, format = 'd', big.mark = ','),
            paste(vb_pct_new_users, "%",sep=""),
            paste(vb_pct_view_cart, "%",sep=""),
            paste(vb_pct_reach_checkout, "%",sep="")),
  info = c("unique users",
           "new users",
           "viewed their cart",
           "reached checkout"),
  font_family = c(rep("EmojiOne",4)),
  color = factor(1:4)
)

vb_plot(df)

```

```{r message=FALSE, warning=FALSE}

# COLUMN CHART (traffic)[variable vs. sum]
#------------------------------>

df <- data.frame("orders_placed" = sum(orders$orders_placed), 
                 "checkout_page_views" = sum(traffic$reach_checkout), 
                 "cart_views" = sum(traffic$view_cart))

df <- df %>% 
  pivot_longer(cols=everything()) %>%
  mutate(name = factor(name, levels = c("cart_views", "checkout_page_views", "orders_placed")))

cols <- c("orders_placed"="darkgreen",
          "checkout_page_views"="darkolivegreen4", 
          "cart_views"="darkolivegreen2")

df %>% 
  ggplot(aes(x = name, y=value, fill=name)) +
  labs(title="Order Funnel",
       x="event",
       y="number of occurrences") +
  geom_col(alpha = 0.8) +
  scale_color_manual(values = cols,
                     aesthetics = c("color", "fill"),
                     guide = FALSE) +
  style

```



```{r message=FALSE, warning=FALSE}

# COLUMN CART (traffic)[source/medium vs sessions]
#------------------------------>

df <- traffic %>% 
  #group by source/medium
  group_by(source, medium) %>%
  #format source/medium for label
  mutate("source_medium" = paste(source, medium, sep = " / "),
         "sessions" = n()) %>%
  ungroup() %>%
  filter(sessions >= 10) %>%
  select(source_medium, sessions) %>%
  unique()

df$source_medium <- factor(df$source_medium, 
                           levels = df$source_medium[order(df$sessions, decreasing = TRUE)])

df %>%
  ggplot(aes(x = source_medium, y = sessions)) + 
  geom_col_base +
  labs(title="Website Visits",
       x="source / medium",
       y="number of website visits") +
  style

```


# Coupons

```{r message=FALSE, warning=FALSE}


# VALUE BOX (coupons)
#------------------------------>

# assign variables

vb_coupon_orders <- sum(coupon$total_orders)
vb_coupon_discounts <- sum(coupon$total_discounts)

# create df of parameters

df <- data.frame(
  x = c(2,12), # position of box
  y = c(1,1), # position of box
  h = rep(5,2), # size of box
  w = rep(9,2), # size of box
  value = c(vb_coupon_orders,
            paste("$",formatC(vb_coupon_discounts, format = 'd', big.mark = ','), sep="")),
  info = c("discounted orders",
           "total discounts"),
  font_family = c(rep("EmojiOne",2)),
  color = factor(1:2)
)

vb_plot(df)

```


```{r message=FALSE, warning=FALSE}

# COLUMN CART (coupons)[number of orders and amount discounted]
#------------------------------>

df <- coupon

#amount discounted
df %>% 
  ggplot(aes(x = coupon_code, y = total_discounts)) +
  geom_col_base +
  labs(title="Discounts",
       x="coupon code",
       y="amount discounted") +
  style + theme(aspect.ratio = 0.6)

#number of orders

df %>% 
  ggplot(aes(x = coupon_code, y = total_orders)) +
  geom_col_base +
  labs(title="Coupon Applications",
       x="coupon code",
       y="number of applications") +
  style + theme(aspect.ratio = 0.6)



```

# Campaigns

```{r, message=FALSE, warning=FALSE}

# COLUMN CHART (total clicks)
#------------------------------>

df <- campaign %>%
  pivot_longer(!c(source, campaign), names_to = "metric", values_to = "value") %>%
  filter(metric == "click")

cols <- c("facebook" = "steelblue",
          "newsletter" = "yellow2")

df %>% ggplot(aes(x = campaign, y = value, fill = factor(source))) +
  labs(title="Campaign Link Clicks",
       x="campaign",
       y="number of clicks") +
  geom_col(position = "stack", alpha = 0.8) +
  scale_color_manual(values = cols,
                     aesthetics = c("color", "fill")) +
  style + theme(aspect.ratio = 0.6,
               legend.position = "right")



# COLUMN CHART (view_cart , reach_checkout)
#------------------------------>

df <- campaign %>%
  pivot_longer(!c(source, campaign), names_to = "metric", values_to = "value") %>%
  filter(metric != "click")

cols <- c("facebook" = "steelblue",
          "newsletter" = "yellow2")

df %>% ggplot(aes(x = metric, y = value, fill = source)) +
  labs(title="Campaign Order Funnel",
       x="event",
       y="number of occurences") +
  facet_wrap(~campaign) +
  geom_col(position = "stack", alpha = 0.8) +
  scale_color_manual(values = cols,
                     aesthetics = c("color", "fill")) +
  style + theme(strip.background = element_rect(colour = "grey40", fill = NA),
                panel.border = element_rect(color = "grey40", fill=NA),
                aspect.ratio = 1,
                legend.position = "right")

```
